import {WarningScore} from './warning-score.model';

export class Patient {
  _id: number;
  firstName: string;
  lastName: string;
  dateOfBirth: Date;
  sex: string;
  address: string;
  contact: string;
  travelToRiskCountriesInTheLast14Days?: boolean | string;
  contactInTheLast14DaysWithAPersonWhoHasSymptoms?: boolean;
  haveYouBeenInContactWithPeopleWhoHaveTheCoronaVirusInTheLast14Days?: boolean;
  haveYouEverBeenToAHealthCareFacilityWhereTheDiseaseHasBeenDiagnosedWithANewCoronavirus?: boolean;
  didYouGoForAExaminationSomewhere?: boolean;
  currentProblems?: string[];
  problemsDuration: number;
  highTemperature?: boolean | string;
  shaking?: boolean;
  lossOfAppetite?: boolean;
  exhaustion?: boolean;
  muscleAchesAndPains?: boolean;
  boneOrJointPain?: boolean;
  cough?: boolean;
  expectoration?: boolean;
  shortnessOfBreath?: boolean;
  choking?: boolean;
  fatigue?: boolean;
  chestPressure?: boolean;
  chestPain?: boolean;
  sneezing?: boolean;
  nasalCongestion?: boolean;
  secretionFromTheNose?: boolean;
  bleedingFromTheNose?: boolean;
  eyesPain?: boolean;
  redEyes?: boolean;
  throatProblems?: boolean;
  throatSecretion?: boolean;
  headache?: boolean;
  abdominalPain?: boolean;
  nausea?: boolean;
  vomit?: boolean;
  diarrhea?: boolean;
  backPain?: boolean;
  urinaryProblems?: boolean;
  rash?: boolean;
  enlargedLymphNodes?: boolean;
  neuroInterferences?: boolean;
  drugAllergy?: boolean;
  smoking?: boolean;
  increasedBloodPressure?: boolean;
  coronaryHeartDisease?: boolean;
  heartArrhythmia?: boolean;
  heartFailure?: boolean;
  lungDisease?: boolean;
  asthma?: boolean;
  chronicKidneyDisease?: boolean;
  diabetes?: boolean;
  heartStroke?: boolean;
  malignantDisease?: boolean;
  chronicLiverDisease?: boolean;
  inflamatoryBowelDisease?: boolean;
  reuma?: boolean;
  hiv?: boolean;
  medications?: string[];
  operations?: string[];
  warningScores: WarningScore[];
}
